version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
